### ISSUE TITLE
HRD account can edit a property listing

### ISSUE THREAD

**Issue by elenm** [CityOfDetroit/bloom#83] opened 2021-06-09 14:25 UTC
- [x] When HRD edits a listing, they are directed to a form that's auto-populated with the listing's existing data.
- [ ] Any changes made to the form are saved to the database when the form is submitted.

**Comment by willrlin** [comment] 2021-06-29 12:56
Abbie have you started working on making this a numeric field? From Tom's mocks it generally just looks like a boolean for each type of unit.

**Comment by abbiefarr** [comment] 2021-06-29 16:45
No not yet. I changed this issue to encompass all listing edits now that we have the existing partner portal. Planning on waiting to fool with the availability section until we come to a consensus on the data structure the city wants.

**Comment by avaleske** [comment] 2021-06-30 06:45
Is this a duplicate of #126 ?

**Comment by willrlin** [comment] 2021-06-30 12:52
Closed the other one as a duplicate. I had created the same issue in two separate epics.

**Comment by pfeeny5** [comment] 2021-07-09 18:34
Confirming ability to edit via admin portal.
![image](https://user-images.githubusercontent.com/82653098/125121994-c3e87200-e0c2-11eb-9b2d-7203d28fc090.png)

Additionally, edit stays when viewing in public portal.
![image](https://user-images.githubusercontent.com/82653098/125122021-d2368e00-e0c2-11eb-980d-64bdd303b8ac.png)

**Closed** 2021-07-09 19:56 UTC
Labels: M7, epic: partner portal, size: 8
