### ISSUE TITLE
(Detroit) All pages - skip to main content

### ISSUE THREAD

**Issue by sarahlazarich** [CityOfDetroit/bloom#1530] opened 2023-01-23 19:06 UTC
**User Story:**
As a….Person using a screen reader
I want…To skip to the main content on each page on our site
So that…I can efficiently navigate to information that is most important to me

**Additional detail:**

- The user is not able to skip to main content on any pages on our site
- This ticket applies to the Detroit bloom instance

**Design Asset Documentation:**
Required (Y/N) Y
(If yes) link here: [Skip Link Asset](https://www.figma.com/file/NOm8rRr97oFBnv1d2i3xy4/detroit-general?node-id=405%3A1418&t=6XKSCzfGM6eguupD-0)

**Technical Notes:**
Change to UI components? (Y/N)

**Lighthouse recommendation:**
Add a skip to the main content link into the code for each web page template.

**Technical notes:**
Will this require a change to UI components?

**Acceptance criteria:**
Given that I am a person using a screen reader on desktop
When I wish to skip to the main content on the page
Then I can do so quickly and easily using a “skip to main content” link

Given that I am a person using a screen reader on mobile
When I wish to skip to the main content on the page
Then I can do so quickly and easily using a “skip to main content” link

**QA review instructions:**

(Desktop testing instructions)
(Mobile testing instructions)

**Comment by sarahlazarich** [comment] 2023-01-26 15:01
@ColinBuyck @eajensenwa -- updated with asset!

**Comment by emilyjablonski** [comment] 2023-03-08 22:54
Duplicate of https://github.com/bloom-housing/bloom/issues/3310

**Closed by emilyjablonski** 2023-03-08 22:54 UTC
