### ISSUE TITLE
[Copy Change] Change wording of 'Do I Qualify' button on listings page

### ISSUE THREAD

**Issue by GabeBenjamin** [CityOfDetroit/bloom#692] opened 2021-10-19 19:24 UTC
Change wording of 'Do I Qualify' button on listings page

![image](https://user-images.githubusercontent.com/371177/137976945-59858665-0e4e-4568-9219-2c0415ea7980.png)

**Comment by GabeBenjamin** [comment] 2021-10-19 19:24
@jnowell what should the button say?

**Comment by jnowell** [comment] 2021-11-03 17:44
This is actually obsolete due to the recent homepage changes. Closing. We have a similar 'Do I Qualify' button on the Listing Detail page, but Safiya wants to leave it.

**Comment by jnowell** [comment] 2021-11-03 17:57
Actually take that back. This issue was intended to refer to the 'Do I Qualify' button on the Listing Details page. Safiya would like the new copy of the button to be 'Check Your Housing Qualifications'.

**Closed** 2021-11-05 00:25 UTC
Labels: M14
