### ISSUE TITLE
[Eligibility Questionnaire] Add button or link to the questionnaire

### ISSUE THREAD

**Issue by elenm** [CityOfDetroit/bloom#224] opened 2021-07-20 16:38 UTC
Add the button or menu item that redirects to the eligibility questionnaire.

**Comment by willrlin** [comment] 2021-07-28 17:57
Are you planning to put that on the front page? I think #118 is a duplicate of this if so. I'll close that one.

**Comment by ChelseaRucker** [comment] 2021-08-02 20:39
<img width="1440" alt="Screen Shot 2021-08-02 at 3 39 20 PM" src="https://user-images.githubusercontent.com/11837745/127920917-672df040-ae64-4193-b389-813fb0426962.png">

**Closed** 2021-08-04 14:09 UTC
Labels: M9, P0, epic: eligibility questionnaire
