### ISSUE TITLE
Add accessibility features tables to hold structured accessibility data

### ISSUE THREAD

**Issue by avaleske** [CityOfDetroit/bloom#609] opened 2021-09-21 20:57 UTC
This originated from #67.

### Context:
We need to add structured accessibility data, so we can filter and search on it, and show more consistent accessibility information to users.

We have a [form](https://docs.google.com/spreadsheets/d/1c26wYmXv77lAVcuTLvQ4F0wO5Lixgbh5En18ONXH_bc/edit#gid=1400452947) we've been sending to property managers, and collected some accessibility data that we need to be able to store.

### Work:
1. We need to add two tables:
   - UnitAccessibilityFeatures to store unit-specific features that foreign-keys to the listing
   - BuildingAccessibilityFeatures to store building-specific features that foreign-keys to the listing
2. Add some seed listings that use this data and seed the database with the right accessibility features. (Maybe that's part of the migration?)

I'm not sure if it will be best to store these as
- 1 feature per row, with columns for the feature name, the key, and whether all/some/none of the units have the feature
- 1 building per row, with columns for each feature.
Probably the first one is better.

### The questions asked in the form are:
1) Do any units in your building have the following accessibility features for residents with disabilities?

- [In Unit Washers and Dryers]
- [Barrier-free entrances (meaning no steps or ramps are needed to get into a unit)]
- [Doorways to units are big enough for a wheelchair]
- [Roll-in shower for residents using wheelchairs]
- [Grab bars in bathrooms]
- [Lowered light switches for those using wheelchairs to be able to reach]
- [Lowered cabinets for those using wheelchairs to be able to reach]

Property Managers are able to provide the following responses for each category: 

- No units in this building have these features
- All units in property have these features
- Only specific "accessible units" have these features

2) Does your building offer any of the following accessibility features? These answers will help residents with disabilities understand if this property can meet their needs.
Property Managers can select any of the following options:
- Elevator
- Laundry room
- Allows service animals
- Handicapped parking spots
- Doorways to property are big enough for a wheelchair
- Units accessible for those with mobility-related disabilities
- Units accessible for those with vision-related disabilities
- Units accessible for those with hearing-related disabilities

### Done
Done is when these tables exist and we've contributed the upstream.

### Other considerations:
The listing form in the partner portal lets you add an Accessibility Priority Type to the summary. I'm not sure how that intersects with this:
![image](https://user-images.githubusercontent.com/1295824/134246511-8e650efe-fbec-464f-8788-e27a8750f89e.png)

**Comment by willrlin** [comment] 2021-09-22 13:49
This seems like a really complex solution. I'm wondering how much of it is caused by the fact that the property managers can answer "none", "all", or "some" to which units have these. Do we know what kind of data we're actually getting in response to these questions?

I'm also thinking about what kind of data would be available via rentlinx about the building/units for future automation.

**Comment by jnowell** [comment] 2021-11-12 16:28
After doing some accessibility testing, here are the features that we'd like to add. These are all boolean features that will be stored at the building level (the complexities that Will mentioned in his previous comment, combined with the limited time left, seem to make unit-level properties out of scope). Exact labels are TBD:

Elevator
Wheelchair Ramps 
Allows service animals
Accessible parking 
In unit washer and dryer
Barrier-free unit entrances
Roll-in shower
Grab Bars
Laundry in building 
Parking on site 
Heating in unit
AC in unit

**Closed** 2021-12-15 18:07 UTC
Labels: size: 5, epic: data architecture, epic: styling + layout, M17
